name: CI-arm

on:
  workflow_dispatch:

  release:
    # this runs CI only when a release is created at first (and not when it is
    # edited or published)
    types: [created]


jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      CONTAINER_PATH: /tmp/fs
      EMFLAVOUR: 3.1.61
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Display CI properties
      run: |
        WD=$(pwd)
        python3 -V
        echo $WD
        echo
        clang --version | head -n 1
        echo
        gcc --version | head -n 1
        echo "Node :"
        node -v
        echo
        echo "Github env:"
        env|grep GITHUB
        sudo apt-get install libtalloc2 lz4

    - name: prepare build env
      run: |
        git clone https://github.com/pygame-web/python-wasm-sdk
        mkdir -p /tmp/fs/tmp/sdk/dist /tmp/dist

    - name: Build sdk (debian docker) for python 3.12
      run: |
        docker run -e EMFLAVOUR=3.1.61 -e BUILDS=3.12 -v ./python-wasm-sdk:/workspace -v /tmp/fs/tmp/sdk/dist:/tmp/sdk/dist  --workdir=/workspace --name wasmsdk-3-12 debian:stable ./python-wasm-sdk.sh
        mv /tmp/sdk/dist/*.tar.lz4 /tmp/dist/

    - name: Build sdk (debian docker) for python 3.13
      run: |
        docker run -e EMFLAVOUR=3.1.61 -e BUILDS=3.13 -v ./python-wasm-sdk:/workspace -v /tmp/fs/tmp/sdk/dist:/tmp/sdk/dist  --workdir=/workspace --name wasmsdk-3-13 debian:stable ./python-wasm-sdk.sh
       	mv /tmp/sdk/dist/*.tar.lz4 /tmp/dist/

    - name: Upload sdk to Github Releases
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file:  /tmp/dist/*.tar.lz4
        file_glob: true
        tag: ${{ github.ref }}

