name: CI

on:
  workflow_dispatch:

  release:
    # this runs CI only when a release is created at first (and not when it is
    # edited or published)
    types: [created]

  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      CONTAINER_PATH: /tmp/fs
      EMFLAVOUR: 3.1.61
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Display CI properties
      run: |
        WD=$(pwd)
        python3 -V
        echo $WD
        echo
        clang --version | head -n 1
        echo
        gcc --version | head -n 1
        echo "Node :"
        node -v
        echo
        echo "Android support:"
        echo
        echo "Github env:"
        env|grep GITHUB
    - name: Build sdk
      run: |
        bash ./proot.sh
    - name: Upload sdk to Github Releases
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/fs/tmp/sdk/*.tar.lz4
        file_glob: true
        tag: ${{ github.ref }}

